### ISSUE TITLE
Repository license?

### ISSUE THREAD

**Issue by tanuva** [mbarnig/WKWebView#3]
Hi Marco,

I would like to use a slightly stripped down version of this project as a simple WKWebView tester. To do that legally I'd need a license for your code though, what would you choose?

(Github should recognize and display the license automatically If you put the text into `LICENSE` in the toplevel directory of the repo.)

**Comment by mbarnig** [comment]
Hello Marcel,
I added the MIT license to the repository which is qualified as short and simple. I hope this meets your needs.

**Comment by tanuva** [comment]
Perfect, thank you! :)
